- .circleci/config.yml
- assets/javascripts/mirrorcache.js
- lib/MirrorCache/Schema/ResultSet/Acc.pm
- lib/MirrorCache/Schema/ResultSet/Folder.pm
- lib/MirrorCache/WebAPI/Plugin/Backstage.pm
- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- t/environs/04-remote.sh
- t/environs/05-rest-server.sh
- templates/dir.html.ep
- templates/layouts/navbar.html.ep
The new header also provides functionality:
- Aggregation stats about folder;
- List of mirrors where folder is up to date;
- List of mirrors where folder is outdated;
- List of mirrors where folder is missing.
> Add header with mirror stats to Folder form

- doc/setup.md
> Add setup guide

- lib/MirrorCache/Task/MirrorScan.pm
> Attempt to reduce memory usage

- doc/setup.md
- lib/MirrorCache/WebAPI.pm
- t/environs/01-smoke-command.sh
Now it will not perform checks of configuration during simple commands
> Move route initialization into before_server_start

- lib/MirrorCache/WebAPI/Command/backstage/list.pm
- lib/MirrorCache/WebAPI/Command/backstage/run.pm
- script/mirrorcache-backstage
- script/mirrorcache-daemon
[ci skip] to address current limited hardware
> Reduce resource usage in scripts

- lib/MirrorCache/Schema/ResultSet/Server.pm
- lib/MirrorCache/Schema/ResultSet/ServerCapabilityDeclaration.pm
- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
Inaccurate SQL caused server http capabiltiy check skipped when server doesnt support https
> Fix server gets low rank for http when it has https force disabled

- README.asciidoc
- lib/MirrorCache/WebAPI/Controller/Rest/MyIp.pm
- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- lib/MirrorCache/WebAPI/Plugin/Mmdb.pm
- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
- t/environs/05-rest-server.sh
It is not clear what to do if GeoIP fails to detect region properly; at least for testing it is better to not redirect to the headquarter from region.
> Dont redirect unknown

- lib/MirrorCache/Schema/ResultSet/Folder.pm
- lib/MirrorCache/Task/FolderSync.pm
- lib/MirrorCache/Task/MirrorScan.pm
- lib/MirrorCache/WebAPI/Plugin/RootLocal.pm
- lib/MirrorCache/WebAPI/Plugin/RootRemote.pm
This saves memory usage, e.g. 70M RAM for parsing html page with ~7k files
> Rework html parsing without Mojo::DOM

- sql/schema.sql
This speeds up curl -I request from ~0.7 sec to ~0.28 sec
Became noticeable as number of files grows
> Add index on folder_diff_file

- lib/MirrorCache/WebAPI.pm
- t/environs/01-smoke.sh
- templates/layouts/bootstrap.html.ep
For now very basic version detection, may be improved later.
> Add version route and to UI footer

- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- lib/MirrorCache/WebAPI/Plugin/RootRemote.pm
- t/environs/10-remote-fallback-https-redirect.sh
Use it only for actual request redirect, do not use in internal checks
> Tweak MIRRORCACHE_FALLBACK_HTTPS_REDIRECT

- lib/MirrorCache/WebAPI/Plugin/Dir.pm
Not sure why it was there, probably accidental leftower
> Remove unecessary miss_event

- dist/systemd/mirrorcache-backstage.service
- dist/systemd/mirrorcache.service
- doc/setup.md
- t/lib/Dockerfile.systemd
- t/systemd/01-smoke.sh
systemctl -set-environment doesnt survive restart, so use EnvironmentFile instead
> Document how to set environment variables

- doc/setup.md
- Running tests with docker manually
- New cleanup job/task
> Document new cleanup job and running tests with docker manually

- lib/MirrorCache/WebAPI.pm
- lib/MirrorCache/WebAPI/Plugin/Backstage.pm
- lib/MirrorCache/WebAPI/Plugin/Datamodule.pm
- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- lib/MirrorCache/WebAPI/Plugin/Helpers.pm
- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
- t/environs/04-remote-down.sh
This simplifies access to path and geo attributes from different places
> Add datamodule

- lib/MirrorCache/Task/FolderSync.pm
- lib/MirrorCache/WebAPI/Plugin/RootRemote.pm
To make it faster for huge folders
> Add files in one transaction

- assets/javascripts/mirrorcache.js
- templates/dir.html.ep
- templates/layouts/navbar.html.ep
> ui: better cosmetics when no data about folder status

- dist/rpm/MirrorCache.spec
> Simplify spec

- lib/MirrorCache/Schema/Result/Stat.pm
- lib/MirrorCache/WebAPI/Plugin/Datamodule.pm
- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
- lib/MirrorCache/WebAPI/Plugin/Stat.pm
- sql/schema.sql
- t/environs/02-files.sh
- t/environs/03-geo-locations.sh
- t/environs/04-remote.sh
- t/environs/04-rsync.sh
- t/environs/06-remote-geo-dynamic.sh
- t/environs/10-remote-fallback-https-redirect.sh
SQL required during rpm update:
`alter table stat add column metalink boolean default 'f', add column head boolean default 'f'`;
> Add columns head and metalink to stat table

- dist/rpm/MirrorCache.changes
- lib/MirrorCache/Schema/Result/Demand.pm
- lib/MirrorCache/Schema/Result/Folder.pm
- lib/MirrorCache/Schema/ResultSet/AuditEvent.pm
- lib/MirrorCache/Schema/ResultSet/Folder.pm
- lib/MirrorCache/Task/FolderSync.pm
- lib/MirrorCache/Task/FolderSyncSchedule.pm
- lib/MirrorCache/Task/FolderSyncScheduleFromMisses.pm
- lib/MirrorCache/Task/MirrorScan.pm
- lib/MirrorCache/Task/MirrorScanDemand.pm
- lib/MirrorCache/Task/MirrorScanScheduleFromMisses.pm
- lib/MirrorCache/WebAPI/Controller/App/Folder.pm
- lib/MirrorCache/WebAPI/Plugin/Backstage.pm
- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- lib/MirrorCache/resources/migrations/pg.sql
- t/environs/01-smoke-nogeo.sh
- t/environs/01-smoke-plan-scan.sh
- t/environs/02-cleanup.sh
- t/environs/02-files.sh
- t/environs/03-geo.sh
- t/environs/04-remote-down.sh
- t/environs/04-remote.sh
- t/environs/04-rsync.sh
- t/environs/05-remote-geo.sh
- t/environs/06-remote-geo-dynamic.sh
Also dont scan every country when scan of two countries was requested
> Introduce timeout of folder rescan per country

- assets/assetpack.def
- assets/javascripts/admin_user.js
- assets/javascripts/audit_log.js
- assets/stylesheets/admin-pages.scss
- doc/setup.md
- lib/MirrorCache/Events.pm
- lib/MirrorCache/Schema/Result/AuditEvent.pm
- lib/MirrorCache/WebAPI.pm
- lib/MirrorCache/WebAPI/Controller/Admin/AuditLog.pm
- lib/MirrorCache/WebAPI/Controller/Admin/User.pm
- lib/MirrorCache/WebAPI/Controller/Rest/Table.pm
- lib/MirrorCache/WebAPI/Controller/Rest/User.pm
- lib/MirrorCache/WebAPI/Controller/Session.pm
- lib/MirrorCache/WebAPI/Plugin/AuditLog.pm
- lib/MirrorCache/WebAPI/Plugin/Helpers.pm
- t/environs/11-user-management.sh
- t/environs/13-mirror-management.sh
- templates/app/audit_log/index.html.ep
- templates/layouts/navbar.html.ep
Add audit logs page at `/admin/auditlog`
> Audit logs

- doc/setup.md
- lib/MirrorCache/Auth/Fake.pm
- lib/MirrorCache/Auth/OpenID.pm
- lib/MirrorCache/WebAPI.pm
- lib/MirrorCache/WebAPI/Controller/Session.pm
- lib/MirrorCache/WebAPI/Plugin/Helpers.pm
If set to empty string - Fake authentication will be used
> Add MIRRORCACHE_AUTH_URL

- lib/MirrorCache/WebAPI/Plugin/RootRemote.pm
> Consider 403 code as server is reachable

- lib/File/Listing/Rsync.pm
- t/environ/12-file-listing-rsync-init.sh
Before the change stats of symlink itself were collected,
now stats of the linked file will be collected.
> Expand symlinks in rsync root

- dist/rpm/MirrorCache.spec
- run spec-cleaner
- remove perl(URI::Encode) as it's not used
- add the license in the files section
- add perl(Encode)
> dist: rpm spec file update

- dist/salt/profile/mirrorcache/services-init.sls
PR #116 added autodeploy db on start
PR #127 added user mirrorcache without group
> dist: remove obsolete parts in salt

- assets/javascripts/mirrorcache.js
- lib/MirrorCache/Task/FolderSync.pm
- lib/MirrorCache/Task/FolderSyncSchedule.pm
- lib/MirrorCache/Task/MirrorCheckFromStat.pm
- lib/MirrorCache/Utils.pm
- lib/MirrorCache/WebAPI/Controller/Rest/FolderJobs.pm
- lib/MirrorCache/WebAPI/Plugin/Backstage.pm
- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- t/environ/01-smoke-plan-scan.sh
- t/environ/06-remote-geo-dynamic.sh
- t/environ/10-remote-redirect.sh
- templates/app/folder/show.html.ep
- templates/dir.html.ep
- Estimate number of scheduled tasks while trying to to render dir
- Make /rest/folder_jobs/%id async
- ui: move mirror status from dir listing to folder details
- t: fix a typo in t/01-smoke-plan-scan.sh
> Performance improvements

- .github/workflows/test-salt-package-from-obs.yml
- dist/salt/test/Dockerfile
> salt: switch test to use 15.3

- lib/MirrorCache/Datamodule.pm
- lib/MirrorCache/Schema/ResultSet/Stat.pm
- lib/MirrorCache/WebAPI.pm
- lib/MirrorCache/WebAPI/Controller/Rest/Stat.pm
- lib/MirrorCache/WebAPI/Plugin/Stat.pm
- lib/MirrorCache/resources/migrations/pg.sql
- t/environ/06-remote-geo-dynamic.sh
- templates/layouts/navbar.html.ep
It will show individual statistics
> Add /rest/mystat

- lib/MirrorCache/Schema/Result/Project.pm
- lib/MirrorCache/Schema/ResultSet/Project.pm
- lib/MirrorCache/WebAPI.pm
- lib/MirrorCache/WebAPI/Controller/Rest/Project.pm
- lib/MirrorCache/WebAPI/Plugin/Stat.pm
- lib/MirrorCache/resources/migrations/pg.sql
- t/environ/14-project.sh
This is preliminary functionality to specify important folders and requests to see outdated mirrors for them.
More functionality to come.
> Add concept of project

- dist/rpm/MirrorCache.spec
- dist/systemd/mirrorcache-backstage-hashes.service
- script/mirrorcache-backstage-hashes
- script/mirrorcache-daemon
> Add mirrorcache-backstage-hashes.service

- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
- lib/MirrorCache/WebAPI/Plugin/RootRemote.pm
- lib/MirrorCache/WebAPI/Plugin/RootRsync.pm
- t/lib/Dockerfile.environ
Fixes https://github.com/openSUSE/mirrorbrain/issues/66
> Add metalink content-type and content-disposition

- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
- t/environ/01-smoke.sh
> Change origin in metalink to show metalink url

- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- lib/MirrorCache/WebAPI/Plugin/RootLocal.pm
> Show filestamps when rendering files with RootLocal

- lib/MirrorCache/Task/FolderHashesCreate.pm
- lib/MirrorCache/Task/MirrorScan.pm
- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- lib/MirrorCache/WebAPI/Plugin/RootLocal.pm
file->stat call returns nil for broken links, so it needs to be checked
> Fix dir rendering when it had broken links

- lib/MirrorCache/Task/Cleanup.pm
Otherwise pg is slow finding operational mirrors
> Cleanup server_capability_check more aggressively

- lib/MirrorCache/Datamodule.pm
- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- t/environ/02-files-dir.sh
So content of folders can be rendered in json format
> Add parameter JSON for file listing

- lib/MirrorCache/Auth/OpenID.pm
> Add MIRRORCACHE_LOGIN variable

- lib/MirrorCache/WebAPI/Plugin/Dir.pm
Before it did render from DB, unless unknown folder
> Always render files from disk for local root

- lib/MirrorCache/Datamodule.pm
- lib/MirrorCache/Schema/ResultSet/Server.pm
- lib/MirrorCache/Task/Cleanup.pm
- lib/MirrorCache/Task/FolderSync.pm
- lib/MirrorCache/Task/FolderSyncScheduleFromMisses.pm
- lib/MirrorCache/Task/MirrorScan.pm
- lib/MirrorCache/Task/MirrorScanDemand.pm
- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
- lib/MirrorCache/WebAPI/Plugin/RootLocal.pm
- lib/MirrorCache/WebAPI/Plugin/RootRemote.pm
- lib/MirrorCache/WebAPI/Plugin/RootRsync.pm
- t/environ/01-smoke-subtree.sh
- t/environ/02-files.sh
- t/environ/03-geo.sh
- t/environ/08-folder-delete.sh
- t/environ/15-local-symlink.sh
* Sync only real location, reuse results for symlinked locations
* Scan mirrors for both locations
* Find mirrors that have file in both real and symlinked locations
> Add proper handling of local symlinks

- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
- t/environ/03-geo-mirrorlist.sh
Without this change @avoid_countries becomes corrupted somehow and includes country from previous request
> Fix mirrorlist for the same region

- lib/MirrorCache/WebAPI/Plugin/Backstage.pm
- t/environ/07-async-recurs.sh
- t/lib/environ/mc/source/backstage/start.sh.m4
- t/manual/01-download.o.o.sh
And tune some parameters to be able browse unknown folders when backstage is busy
> Add script for manual testing download.o.o

- dist/systemd/mirrorcache-backstage-hashes.service
- dist/systemd/mirrorcache-backstage.service
> Add RestartSec to backstage systemd files

- lib/MirrorCache/WebAPI/Plugin/Dir.pm
> Add promise timeout for rendering unknown folder

- lib/MirrorCache/WebAPI.pm
- t/environ/01-smoke.sh
- templates/branding/default/footer.html.ep
- templates/branding/openSUSE/footer.html.ep
> Add config CUSTOM_FOOTER_MESSAGE

- dist/systemd/mirrorcache-hypnotoad.service
- dist/systemd/mirrorcache.service
> Tweak systemd files

- lib/MirrorCache/Datamodule.pm
- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
- lib/MirrorCache/WebAPI/Plugin/Stat.pm
- lib/MirrorCache/WebAPI/Plugin/Subsidiary.pm
- t/environ/16-rescan-no-country.sh
Addresses https://progress.opensuse.org/issues/114953
> Rescan if no country hit

- assets/javascripts/browse.js
- assets/stylesheets/overall.scss
- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- lib/MirrorCache/WebAPI/Plugin/Helpers.pm
- t/environ/04-remote-nginx.sh
- templates/browse.html.ep
- templates/dir.html.ep
* Show description of top level folders for openSUSE
* Do not access DB in local render for /
* Improve layout for small screen size
> Improve rendering of folders

- assets/javascripts/browse.js
- assets/stylesheets/overall.scss
- lib/MirrorCache/Datamodule.pm
- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
- t/environ/04-remote-nginx.sh
- templates/browse.html.ep
- templates/dir.html.ep
We don't need separate column for metadata, so just provide url in size/mtime columns
> ui: Move mirrorlist url to size/mtime column

- lib/MirrorCache/Schema/ResultSet/Folder.pm
- lib/MirrorCache/Task/FolderSync.pm
- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- lib/MirrorCache/WebAPI/Plugin/RootRemote.pm
- t/environ/04-remote-link.sh
Before this commit it worked only with nfs access
> Detect redirects with remote root

- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- lib/MirrorCache/WebAPI/Plugin/RootRemote.pm
- t/environ/04-remote-mc.sh
- t/manual/01-download.o.o.sh
This will provide size and mtime from another MirrorCache instance during sync
> Add json parsing to FolderSync task

- assets/javascripts/admintable.js
- lib/MirrorCache/Config.pm
- lib/MirrorCache/Schema/Result/MyServer.pm
- lib/MirrorCache/Schema/Result/Server.pm
- lib/MirrorCache/Schema/Result/ServerCapabilityDeclaration.pm
- lib/MirrorCache/Schema/ResultSet/Server.pm
- lib/MirrorCache/Task/Cleanup.pm
- lib/MirrorCache/Task/MirrorProviderSync.pm
- lib/MirrorCache/WebAPI.pm
- lib/MirrorCache/WebAPI/Controller/Rest/ServerLocation.pm
- lib/MirrorCache/WebAPI/Controller/Rest/Table.pm
- lib/MirrorCache/WebAPI/Plugin/Backstage.pm
- t/environ/01-smoke-mirror-provider.sh
- templates/app/myserver/index.html.ep
- templates/app/server/index.html.ep
> Add MIRROR_PROVIDER to share mirror list

- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
Accidentally size of folder was checked instead of size of file
> Fix REDIRECT_HUGE with local files

- assets/javascripts/browse.js
> ui: Dont encode colon character in file names

- assets/javascripts/browse.js
- lib/MirrorCache/Schema/Result/Hash.pm
- lib/MirrorCache/Schema/ResultSet/File.pm
- lib/MirrorCache/Schema/ResultSet/Hash.pm
- lib/MirrorCache/Task/FolderHashesCreate.pm
- lib/MirrorCache/Task/FolderHashesImport.pm
- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
- lib/MirrorCache/resources/migrations/Pg.sql
- lib/MirrorCache/resources/migrations/mysql.sql
- t/environ/02-files-hashes-import.sh
- t/environ/02-files-hashes.sh
- templates/mirrorlist.html.ep
> Add sha512 to hash

- lib/MirrorCache/WebAPI/Plugin/RootLocal.pm
- lib/MirrorCache/WebAPI/Plugin/RootRemote.pm
> ui: add content-disposition inline to render_file

- dist/salt/profile/mirrorcache/files/usr/share/mirrorcache/sql/projects.sql
- templates/branding/openSUSE/header.html.ep
> Add leap 15.5 to project list

- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- lib/MirrorCache/WebAPI/Plugin/RootLocal.pm
> Add GNOME iso to Current patter

- lib/MirrorCache/Schema/ResultSet/Server.pm
- lib/MirrorCache/WebAPI/Plugin/Project.pm
- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
- t/environ/14-project.sh
The old query uses too much CPU in production
> sql: Optimize lookup for server_project

- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
- t/environ/01-smoke-mirror-hasall-remote.sh
The origin in metalink was turned into comment too early
> Fix value of METALINK_GREEDY in meta4

- lib/MirrorCache/Schema/ResultSet/Stat.pm
- lib/MirrorCache/WebAPI.pm
- lib/MirrorCache/WebAPI/Controller/Rest/Stat.pm
- t/environ/01-smoke.sh
- templates/branding/default/header.html.ep
- templates/branding/openSUSE/header.html.ep
Rework stat sql for mariadb to use hour aggregations
Fix sql for previous period in /rest/stat because of missing index
Remove 'My Statistics' menu item
> Rework and fix /rest/stat

- lib/MirrorCache/Datamodule.pm
- lib/MirrorCache/Schema/ResultSet/Stat.pm
Also fix a typo in the handling of content.asc files
> Update regexps to handle zstd and sha512

- assets/javascripts/reportdownloadtable.js
- lib/MirrorCache/WebAPI/Controller/Report/Download.pm
- lib/MirrorCache/WebAPI/Controller/Rest/ReportDownload.pm
- t/environ/20-report-download.sh
- templates/report/download/index.html.ep
Added support for mirror,country,type,os,os_version,arch,project
> Add url parameters for report/download

- lib/MirrorCache/Schema.pm
- lib/MirrorCache/Schema/Result/Server.pm
- t/environ/13-mirror-management.sh
> Add flag mysql_enable_utf8mb4 when connectin to MariaDB

- lib/MirrorCache/Datamodule.pm
- lib/MirrorCache/WebAPI/Plugin/Dir.pm
- lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
- lib/MirrorCache/WebAPI/Plugin/RootLocal.pm
- t/environ/01-smoke-current.sh
- t/environ/03-headquarter-subsidiaries-hashes.sh
- t/environ/04-remote-current-no-nfs.sh
- t/environ/04-remote-current.sh
- t/environ/04-remote-nfs.sh
Redirect to a mirror which has the file to which the symlink is pointing
> Smart handle of local symlinks

- dist/systemd/mirrorcache-backstage-hashes.service
- dist/systemd/mirrorcache-backstage.service
> systemd: for background services LOG_LEVEL=error and MemoryMax

- lib/MirrorCache/Utils.pm
> Use urandom for random_string

- assets/javascripts/browse.js
- assets/javascripts/package.js
> ui: change default sort order for mtime column

- script/mirrorcache-backstage
- script/mirrorcache-backstage-hashes
> Add BACKSTAGE_QUEUE parameter to backstage startup scripts
