openSUSE/MirrorCache

.circleci/config.yml, lib/DBIx/Class/Timestamps.pm, lib/MirrorCache/Schema/ResultSet/Folder.pm, lib/MirrorCache/Task/FolderSync.pm, lib/MirrorCache/Task/FolderSyncScheduleFromMisses.pm, lib/MirrorCache/WebAPI/Plugin/Dir.pm, lib/MirrorCache/WebAPI/Plugin/RootRemote.pm, t/environs/04-remote-link.sh
Let MirrorCache redirect directory listing to another directory when remote root does the same.
Use localtime everywhere instead of UTC.
=> Redirect when remote root redirects

assets/assetpack.def, assets/javascripts/admin_user.js, lib/MirrorCache/WebAPI.pm, lib/MirrorCache/WebAPI/Controller/Admin/User.pm, lib/MirrorCache/WebAPI/Controller/Rest/User.pm, t/environs/11-user-form.sh, t/environs/11-user-management.sh, templates/app/user/index.html.ep, templates/layouts/navbar.html.ep
=> Add Users page for user management

lib/MirrorCache/Schema/ResultSet/Server.pm
It looks postgres applies folder/files filter too late.
The change decreases query execution on 600 folders and ~200K files from 4s down to ~0.5s
=> Optimize mirrors sql

lib/MirrorCache/Task/FolderSyncScheduleFromMisses.pm, lib/MirrorCache/WebAPI/Plugin/Dir.pm, t/environs/04-remote-link.sh
This is not needed because we schedule FolderSync anyway to render it.
Plus it solves problem when rows in folder table are created for symlinks by ScheduleFromMisses job.
=> Dont log miss event for folder request

doc/setup.md, lib/MirrorCache/Schema/ResultSet/Server.pm, lib/MirrorCache/WebAPI/Plugin/RootRemote.pm, t/environs/09-stability-force.sh
1. Do not suggest http mirrors for https requests and vice versa. (Before different schema had just lower priority).
2. Require presence of a row in server_capability_check for a redirect candidate. (Unless no checks are present at all for the country). 
3. Introduce MIRRORCACHE_FALLBACK_HTTPS_REDIRECT variable.
=> Enforce strict scheme handling

t/lib/test-in-container-environs.sh
- Introduces possibility to keep a test container runing, if `EXPOSE_PORT` is set to the port inside of container you want to map to port 80 on the host: `EXPOSE_PORT=3190` for a `mc9` mirrorcache instance will make MirrorCache available at localhost:80
- Also, if `MIRRORCACHE_CITY_MMDB` is set, it will start the container with that, for example: `MIRRORCACHE_CITY_MMDB=/path/to/file` results in:
`docker run --env MIRRORCACHE_CITY_MMDB=/path/to/file -v /path/to/file:/path/to/file`
=> Add a way to keep MirrorCache container running

lib/MirrorCache/Schema/Result/FolderDiffServer.pm, lib/MirrorCache/Schema/ResultSet/Folder.pm, lib/MirrorCache/Schema/ResultSet/FolderDiffServer.pm, lib/MirrorCache/Schema/ResultSet/Server.pm, lib/MirrorCache/Task/MirrorScan.pm, sql/schema.sql, t/environs/02-cleanup.sh, t/environs/04-remote.sh
Before this it did store hash of present files.
With new change adding files to both root and mirror should result in the same hash
=> Rework folder_diff to store hash of missing files

lib/MirrorCache/Schema/ResultSet/Server.pm
After deployment problem rows must be cleaned with sql command:
```
delete from folder_diff_server where (folder_diff_id, server_id) in (select fds1.folder_diff_id, fds1.server_id from 
folder_diff_server fds1 
join folder_diff fd1 on fd1.id = fds1.folder_diff_id
join folder_diff_server fds2 on fds1.server_id = fds2.server_id and fds1.dt < fds2.dt
join folder_diff fd2 on fd2.id = fds2.folder_diff_id and fd1.folder_id = fd2.folder_id);
```
=> Fix bug populating rows in folder_diff_server

dist/salt/profile/mirrorcache/files/usr/share/mirrorcache/sql/mirrors-eu.sql, dist/salt/profile/mirrorcache/files/usr/share/mirrorcache/sql/mirrors-na.sql, sql/schema.sql
Add unique index on hostnames
so that salt cannot import all servers multiple times.
For this we have to drop some duplicate mirror server entries.
=> Add unique index on hostnames

assets/stylesheets/overall.scss, assets/stylesheets/tables.scss, templates/dir.html.ep
[skip ci] Previously values in date and size columns might wrap into two lines when filename is long.
This change attempts to make sure that only filename can wrap.
=> ui: css wrap only filename

dist/rpm/MirrorCache-tmpfilesd.conf, dist/rpm/MirrorCache-user.conf, dist/rpm/MirrorCache.spec
Based on:
- [users and groups packaging guidelines](https://en.opensuse.org/openSUSE:Packaging_guidelines#Users_and_Groups)
- [systemd packaging guidelines](https://en.opensuse.org/openSUSE:Systemd_packaging_guidelines#Creating_files_and_subdirectories_in_.2Fvar.2Frun_and_.2Frun)
=> Rework creation of mirrorcache user and its home dir

lib/MirrorCache/WebAPI/Plugin/Dir.pm, lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm, t/environ/06-remote-geo-root-country-same-region.sh
In situation when:
- metadata is requested;
- there is no mirror;
- MIRRORCACHE_ROOT_COUNTRY=1;
the path_miss was not scheduled so the scan did not happen.
=> Schedule scan when main server serves as a mirror

lib/MirrorCache/WebAPI/Plugin/Datamodule.pm, lib/MirrorCache/WebAPI/Plugin/Helpers.pm, lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm, lib/MirrorCache/WebAPI/Plugin/RootRemote.pm, lib/MirrorCache/WebAPI/Plugin/Stat.pm, t/environ/06-remote-geo-root-country.sh, t/lib/Dockerfile.environ, t/lib/Dockerfile.systemd
* Truncate country code to two letters
* Log trailing slash in stat 
* t: Replace repo in docker to openSUSE:infrastructure
* Fix double stats when no mirror in country
* Fix concat undef when MIRRORCACHE_BRANDING is not set
=> Small fixes

lib/MirrorCache/Datamodule.pm, lib/MirrorCache/Schema/ResultSet/AuditEvent.pm, lib/MirrorCache/Schema/ResultSet/Stat.pm, lib/MirrorCache/Task/FolderSync.pm, lib/MirrorCache/Task/FolderSyncScheduleFromMisses.pm, lib/MirrorCache/Task/MirrorScanScheduleFromMisses.pm, lib/MirrorCache/Task/MirrorScanScheduleFromPathErrors.pm, lib/MirrorCache/WebAPI/Plugin/AuditLog.pm, lib/MirrorCache/WebAPI/Plugin/Backstage.pm, lib/MirrorCache/WebAPI/Plugin/Dir.pm, lib/MirrorCache/WebAPI/Plugin/Mmdb.pm, lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm, lib/MirrorCache/WebAPI/Plugin/RootLocal.pm, lib/MirrorCache/WebAPI/Plugin/Stat.pm, lib/MirrorCache/resources/migrations/pg.sql, t/environ/01-smoke-plan-scan.sh, t/environ/01-smoke.sh, t/environ/02-files.sh, t/environ/04-remote-nginx-redirect.sh, t/environ/04-remote-nginx.sh, t/environ/04-remote.sh, t/environ/04-rsync.sh, t/environ/06-remote-geo-dynamic.sh, t/lib/environ/mc/source/gen_env.sh.m4, t/lib/environ/mc/source/sql.sh.m4, t/lib/environ/mc/source/sql_test.sh.m4
Historically table audit_event was used to schedule jobs
Since stat table was introduced to show similar info, it is more convenient to use it for scheduling.
Events for miss and hit are not logged anymore.
New columns folder_id and file_id are added to stat table, they are used to distinguish path_miss vs mirror_miss.
=> Schedule jobs from stat

lib/MirrorCache/Schema/ResultSet/Server.pm, lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm, t/environ/10-remote-redirect.sh
Previously such mirrors were just given lower priority.
We still show them in mirrorlist still, just with http
=> Fix redirect to https when mirror doesnt have it

lib/MirrorCache/Schema/ResultSet/Hash.pm, lib/MirrorCache/Task/FolderHashesImport.pm, lib/MirrorCache/WebAPI/Plugin/Backstage.pm, lib/MirrorCache/WebAPI/Plugin/Dir.pm, t/environ/02-files-hashes-import.sh
To be implement in another PR:
=> Import file metadata from a headquarter instance to a subsidiary instance

lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm, lib/MirrorCache/WebAPI/Plugin/Stat.pm, t/environ/06-remote-geo-root-country-same-region.sh
And no mirror other mirror found, but root_is_hit() returns 1
(Only metalink and mirrorlist specific)
=> Fix stat reporting as miss when ROOT_COUNTRY is set

lib/MirrorCache/Datamodule.pm, lib/MirrorCache/Schema/ResultSet/Server.pm, lib/MirrorCache/WebAPI/Plugin/Dir.pm, lib/MirrorCache/WebAPI/Plugin/Mmdb.pm, lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm, lib/MirrorCache/WebAPI/Plugin/RootRemote.pm, lib/MirrorCache/WebAPI/Plugin/RootRsync.pm, lib/MirrorCache/resources/migrations/pg.sql, t/environ/04-remote-nginx-redirect.sh, t/environ/04-rsync.sh
MIRRORCACHE_REDIRECT_VPN will be used instead of MIRRORCACHE_REDIRECT if request comes from 10.*
Server gets new column hostname_vpn, which is used when requests comes from 10.*
This way MirrorCache can serve servers which have different hostnames inside vpn.
=> Add support for requests over vpn

doc/setup.md, lib/MirrorCache/Datamodule.pm
MirrorCache can can use column server.hostname_vpn for redirecting
if client IP has prefix as defined by MIRRORCACHE_VPN_PREFIX.
=> Add parameter MIRRORCACHE_VPN_PREFIX

doc/setup.md, lib/MirrorCache/Datamodule.pm, lib/MirrorCache/Task/MirrorLocation.pm, lib/MirrorCache/WebAPI.pm, lib/MirrorCache/WebAPI/Controller/Rest/MyIp.pm, lib/MirrorCache/WebAPI/Plugin/Geolocation.pm, t/lib/Dockerfile.environ
New Geolocation module using Geo::IP2Location.
New env var MIRRORCACHE_IP2LOCATION, but the file extension is checked
anyway: both .mmdb and .BIN are accepted.
=> Add support for IP2Location database

lib/MirrorCache/WebAPI/Plugin/Dir.pm, lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm, lib/MirrorCache/WebAPI/Plugin/Subsidiary.pm, t/environ/03-headquarter-subsidiaries-mirrorlist.sh, t/environ/03-headquarter-subsidiaries.sh, t/environ/10-remote-redirect.sh
when it cannot  be found on the continent.
Do not redirect from subsidiary to headquarter.
=> Find mirror from rest of world

lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm, lib/MirrorCache/WebAPI/Plugin/RootRemote.pm
Static interferes with render_later from before_dispatch, see
https://github.com/mojolicious/mojo/pull/1897
=> Do not use app->static for rendering

lib/MirrorCache/Schema/ResultSet/Server.pm, lib/MirrorCache/Schema/ResultSet/ServerCapabilityDeclaration.pm, lib/MirrorCache/Task/MirrorProbe.pm, lib/MirrorCache/resources/migrations/pg.sql, t/environ/02-cleanup.sh, t/environ/09-stability-01-probe.sh, t/environ/10-https-probe.sh, t/environ/10-ipv-probe.sh
Table server_capability_check now holds only failures.
The main query uses server_stability instead of aggregating over server_capability_check.
=> Add table server_stability

lib/MirrorCache/Schema/Result/Project.pm, lib/MirrorCache/WebAPI/Plugin/Dir.pm, lib/MirrorCache/WebAPI/Plugin/Project.pm, lib/MirrorCache/WebAPI/Plugin/Stat.pm, lib/MirrorCache/resources/migrations/Pg.sql, lib/MirrorCache/resources/migrations/mysql.sql, t/environ/14-project-hq.sh
The goal is to redirect immediatelly if we know that no mirrors have files from subtree on this instance
=> Add configuration for redirect for projects

lib/MirrorCache/Datamodule.pm, lib/MirrorCache/WebAPI/Plugin/Dir.pm, lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm, t/environ/01-smoke-mirror-hasall-remote.sh
To avoid load on main server, metalink will not contain the main server in url list anymore when mirror count exceeds value of METALINK_GREEDY
=> Add parameter METALINK_GREEDY

lib/MirrorCache/WebAPI/Plugin/Dir.pm
Add trailing slash for top folders
to properly link to those directories - as is already the case in [other dirs](http://mirrorcache.opensuse.org/tumbleweed/)
=> Add trailing slash for top folders

lib/MirrorCache/Task/FolderHashesImport.pm, lib/MirrorCache/Task/FolderSync.pm, t/environ/02-files-hashes-import.sh, t/environ/03-headquarter-subsidiaries-hashes.sh
Previously hashes were missing after import in these conditions:
- the headquarter didn't have them yet;
- the calculation on headquarter hasnt finished yet. 
Now the retry will happen if some of new files are still missing hashes.
=> Retry hashes import if a new file hasnt got any

lib/MirrorCache/WebAPI/Plugin/Dir.pm, lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm, lib/MirrorCache/WebAPI/Plugin/RootRemote.pm, t/environ/04-remote-nfs.sh, templates/branding/openSUSE/footer.html.ep
The test 04-remote-nfs was incorrect and didn't test realpath for RootRemote (it was working with mc1 instead of mc2).
This fixes the test and adds missing functionality.
=> Implement realpath for remote root with nfs

lib/MirrorCache/WebAPI/Plugin/Dir.pm, lib/MirrorCache/WebAPI/Plugin/RootLocal.pm, lib/MirrorCache/WebAPI/Plugin/RootRemote.pm, t/environ/04-remote-current-no-nfs.sh, t/environ/04-remote-mc.sh, templates/dir.html.ep
Previosly MirrorCache could properly detect correct redirect for Current.iso files only when files were available on disk.
=> Redirect Current.iso when no nfs mount

lib/MirrorCache/Task/MirrorScan.pm
in mirror_scan when path doesn't exist on mirror
=> Optimise sql for erasing folder_diff_server

lib/MirrorCache/WebAPI/Plugin/Dir.pm, lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm, t/environ/03-headquarter-subsidiaries-remote.sh
when with remote root.
Basically implementation was in wrong place (too early) and the test didn't cover redirection to mirror when needed.
Metalinks worked fine though, so mostly .iso download was impacted only.
=> Fix huge files rendered from REDIRECT_HUGE only for metalink 

templates/branding/openSUSE/footer.html.ep
There are no categories in Bugzilla for MirrorCache which makes it confusing and frustrating.
At very least we should have a bugzilla link to creating a bug there with prefilled category and assignee. Until that time, the README in the source repo is much more helpful.
=> Don't send users to Bugzilla

.circleci/config.yml, .github/workflows/t-systemd.yml, dist/systemd/mirrorcache-subtree.service, t/lib/Dockerfile.systemd.mariadb, t/lib/Dockerfile.systemd.postgresql, t/lib/test-in-container-systemd.sh
There is no need to repeat all parameters in conf-subtree.env, while service file can optionally include conf.env
(needed for subtree state in mirrorcache-formula)
=> Service subtree config

lib/MirrorCache/Datamodule.pm, lib/MirrorCache/WebAPI/Plugin/Dir.pm, t/environ/02-files.sh, t/environ/03-headquarter-subsidiaries.sh
For small files: no cache control
For sensitive files: consistent cache control
For other files: max-age 300 sec
=> Add cache-control options

lib/MirrorCache/Datamodule.pm, lib/MirrorCache/Schema/ResultSet/Stat.pm
The literal dots need to be escaped. Also remove unanchored ".*" as they are very expensive to process
=> Fix escaping in regexps

lib/MirrorCache/WebAPI/Plugin/RenderFileFromMirror.pm
Add a `Vary: Fastly-SSL`
so that caches will not re-use http responses
in https requests.
=> Add a vary Fastly-SSL

lib/MirrorCache/Datamodule.pm
This helps to serve content without adding latency and also avoids most trouble from stale caches
when purging is late or broken.
Also Add stale-if-error
so that the CDN can hide (parts of) outages of MirrorCache
=> Allow caches to serve files while re-checking

lib/MirrorCache/WebAPI.pm, lib/MirrorCache/WebAPI/Controller/Rest/Project.pm, t/environ/14-project-report.sh
The idea is to help to confirm whether a rsync is needed for mirrors
=> Add /rest/project_last_modified route

lib/MirrorCache/WebAPI/Plugin/Dir.pm, t/environ/03-headquarter-subsidiaries-hashes.sh, t/environ/03-headquarter-subsidiaries.sh
Before this the redirect happened only for limited patterns e.g. Media and Current
But since there were introduced many links without these patterns (e.g. #523), 
it was decided to change behavior.
=> Redirect all local symlinks

dist/rpm/MirrorCache-tmpfilesd.conf, dist/systemd/mirrorcache-backstage-hashes.service, dist/systemd/mirrorcache-backstage.service, dist/systemd/mirrorcache-hypnotoad.service, dist/systemd/mirrorcache-subtree.service
[ci skip]
Previous value /tmp/mirrorcache has security implications and was not allowed to Factory
=> systemd: MOJO_TMPDIR=/var/lib/mirrorcache/tmp

lib/MirrorCache/Schema/ResultSet/Server.pm, t/lib/Dockerfile.environ.mariadb.experimental
We exclude all files that might be shipped in repodata with the same name and different mtime
=> Add more exceptions to folder mirrorlist

lib/MirrorCache/Datamodule.pm
We currently have a ttl of roughly 4 minutes. Allowing to serve content for an additional hour calls for inconsistencies. Best practice recommendation is to have it somewhat shorter than ttl.
ref https://www.fastly.com/documentation/guides/concepts/edge-state/cache/stale/ for background information.
=> Reduce stale-while-revalidate time
